# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

paircountxx <- function(x, dr, rmax) {
    .Call('_physx_paircountxx', PACKAGE = 'physx', x, dr, rmax)
}

paircountxy <- function(x, y, dr, rmax) {
    .Call('_physx_paircountxy', PACKAGE = 'physx', x, y, dr, rmax)
}

paircountxx1d <- function(x, dr, rmax) {
    .Call('_physx_paircountxx1d', PACKAGE = 'physx', x, dr, rmax)
}

paircountxy1d <- function(x, y, dr, rmax) {
    .Call('_physx_paircountxy1d', PACKAGE = 'physx', x, y, dr, rmax)
}

kde2stampxx <- function(map, counts, hmax, s, sdmin, sdmax, d, nkernels, kern, kernindex, kernlength) {
    .Call('_physx_kde2stampxx', PACKAGE = 'physx', map, counts, hmax, s, sdmin, sdmax, d, nkernels, kern, kernindex, kernlength)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_physx_RcppExport_registerCCallable', PACKAGE = 'physx')
})
